# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Book_Icon():
    def __init__(self, BookScrollAreaWidgetContents):
        super().__init__()
        self.scrollArea = BookScrollAreaWidgetContents
        self.create_book()

    def create_book(self):
        self.BookImage = QtWidgets.QLabel(self.scrollArea)
        self.BookImage.setGeometry(QtCore.QRect(40, 30, 91, 71))
        self.BookImage.setText("")
        self.BookImage.setPixmap(QtGui.QPixmap("book.png"))
        self.BookImage.setScaledContents(True)
        self.BookImage.setObjectName("BookImage")
        self.Book1_label = QtWidgets.QLabel(self.scrollArea)
        self.Book1_label.setGeometry(QtCore.QRect(70, 90, 51, 31))
        self.Book1_label.setObjectName("Book1_label")
   

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.HistoryWidget = QtWidgets.QScrollArea(self.centralwidget)
        self.HistoryWidget.setGeometry(QtCore.QRect(530, 20, 271, 171))
        self.HistoryWidget.setWidgetResizable(True)
        self.HistoryWidget.setObjectName("HistoryWidget")
        self.HistoryScrollAreaWidgetContents = QtWidgets.QWidget()
        self.HistoryScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 269, 169))
        self.HistoryScrollAreaWidgetContents.setObjectName("HistoryScrollAreaWidgetContents")
        self.HistoryLabel = QtWidgets.QLabel(self.HistoryScrollAreaWidgetContents)
        self.HistoryLabel.setGeometry(QtCore.QRect(120, 0, 47, 13))
        self.HistoryLabel.setObjectName("HistoryLabel")
        self.HistoryWidget.setWidget(self.HistoryScrollAreaWidgetContents)
        self.ActionWidget = QtWidgets.QGroupBox(self.centralwidget)
        self.ActionWidget.setGeometry(QtCore.QRect(530, 190, 271, 211))
        self.ActionWidget.setAlignment(QtCore.Qt.AlignCenter)
        self.ActionWidget.setObjectName("ActionWidget")
        self.TakeOutBookButton = QtWidgets.QPushButton(self.ActionWidget)
        self.TakeOutBookButton.setGeometry(QtCore.QRect(90, 40, 91, 23))
        self.TakeOutBookButton.setObjectName("TakeOutBookButton")
        self.ReturnBookButton = QtWidgets.QPushButton(self.ActionWidget)
        self.ReturnBookButton.setGeometry(QtCore.QRect(90, 80, 91, 23))
        self.ReturnBookButton.setObjectName("ReturnBookButton")
        self.pushButton = QtWidgets.QPushButton(self.ActionWidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 120, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.UserWidget = QtWidgets.QGroupBox(self.centralwidget)
        self.UserWidget.setGeometry(QtCore.QRect(530, 400, 271, 211))
        self.UserWidget.setAlignment(QtCore.Qt.AlignCenter)
        self.UserWidget.setObjectName("UserWidget")
        self.PreviewWidget = QtWidgets.QScrollArea(self.centralwidget)
        self.PreviewWidget.setGeometry(QtCore.QRect(10, 420, 511, 191))
        self.PreviewWidget.setWidgetResizable(True)
        self.PreviewWidget.setObjectName("PreviewWidget")
        self.PreviewScrollAreaWidgetContents = QtWidgets.QWidget()
        self.PreviewScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 189))
        self.PreviewScrollAreaWidgetContents.setObjectName("PreviewScrollAreaWidgetContents")
        self.PreviewContents = QtWidgets.QLabel(self.PreviewScrollAreaWidgetContents)
        self.PreviewContents.setGeometry(QtCore.QRect(150, 70, 311, 101))
        self.PreviewContents.setObjectName("PreviewContents")
        self.PreviewWidget.setWidget(self.PreviewScrollAreaWidgetContents)
        self.BookWidget = QtWidgets.QScrollArea(self.centralwidget)
        self.BookWidget.setGeometry(QtCore.QRect(10, 20, 511, 381))
        self.BookWidget.setWidgetResizable(True)
        self.BookWidget.setObjectName("BookWidget")
        self.BookScrollAreaWidgetContents = QtWidgets.QWidget()
        self.BookScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 379))
        self.BookScrollAreaWidgetContents.setObjectName("BookScrollAreaWidgetContents")
        self.SelectBooks = QtWidgets.QComboBox(self.BookScrollAreaWidgetContents)
        self.SelectBooks.setGeometry(QtCore.QRect(370, 0, 111, 22))
        self.SelectBooks.setEditable(True)
        self.SelectBooks.setObjectName("SelectBooks")
        self.SelectBooks.addItem("")
        self.SelectBooks.addItem("")
        self.BookIcon = Book_Icon(self.BookScrollAreaWidgetContents)
        
        self.BookLabel = QtWidgets.QLabel(self.BookScrollAreaWidgetContents)
        self.BookLabel.setGeometry(QtCore.QRect(220, 0, 47, 13))
        self.BookLabel.setObjectName("BookLabel")
        self.BookWidget.setWidget(self.BookScrollAreaWidgetContents)
        self.PreviewLabel = QtWidgets.QLabel(self.centralwidget)
        self.PreviewLabel.setGeometry(QtCore.QRect(230, 400, 47, 13))
        self.PreviewLabel.setObjectName("PreviewLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HistoryLabel.setText(_translate("MainWindow", "History"))
        self.ActionWidget.setTitle(_translate("MainWindow", "Actions"))
        self.TakeOutBookButton.setText(_translate("MainWindow", "Take out book"))
        self.ReturnBookButton.setText(_translate("MainWindow", "Return book"))
        self.pushButton.setText(_translate("MainWindow", "Preview"))
        self.UserWidget.setTitle(_translate("MainWindow", "User"))
        self.PreviewContents.setText(_translate("MainWindow", "contents"))
        self.SelectBooks.setCurrentText(_translate("MainWindow", "Library Books"))
        self.SelectBooks.setItemText(0, _translate("MainWindow", "Library Books"))
        self.SelectBooks.setItemText(1, _translate("MainWindow", "User Books"))
        self.BookIcon.Book1_label.setText(_translate("MainWindow", "Book 1"))
        self.BookLabel.setText(_translate("MainWindow", "Books"))
        self.PreviewLabel.setText(_translate("MainWindow", "Preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
